language:  generic

notifications:
    slack: nozeio:LIFY1Jtkx0FRcLq3u1WliHRZ

matrix:
    include:
        - os:   Linux
          dist: trusty
          env:  MOD_SWIFT="https://github.com/modswift/mod_swift/archive/0.8.6.tar.gz" SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-4.0-release/ubuntu1404/swift-4.0-RELEASE/swift-4.0-RELEASE-ubuntu14.04.tar.gz"
          sudo: required
        - os:   osx
          osx_image: xcode9

before_install:
    - ./.travis.d/before-install.sh

install:
    - ./.travis.d/install.sh

script:
    - export PATH="$HOME/usr/bin:$PATH"
    - swift build
